apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    type: application
    service: web-server
  name: web-server
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      type: application
      service: web-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  template:
    metadata:
      labels:
        type: application
        service: web-server
        version: "master"
        owner: ""
        timestamp: ""
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        name: web-server
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 60
          timeoutSeconds: 2
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
