apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    type: application
    service: web-server
  name: web-server
spec:
  rules:
  - host: web-server
    http:
      paths:
      - backend:
          serviceName: web-server
          servicePort: 80
