apiVersion: v1
kind: Service
metadata:
  labels:
    type: resource
    service: elasticsearch
  name: elasticsearch
spec:
  type: ClusterIP
  selector:
    type: resource
    service: elasticsearch
  sessionAffinity: None
  ports:
  - name: http
    port: 9200
    protocol: TCP
