apiVersion: v1
kind: Service
metadata:
  labels:
    type: resource
    service: redis
  name: redis
spec:
  type: ClusterIP
  selector:
    type: resource
    service: redis
  sessionAffinity: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
